/*
 * Pure C 2019
 * ex7a2.c
 *
 * This is a client to rpc server.
 *
 *  Created on: Dec 27, 2018
 *        Created by Tasneem Abu Odeh - id: 314902685 - login: tasnimab.
 *             Jouana Nusralla - id:312315104 - login: jouananu.
 *
 *
 * This client gets a number 0-3..
 * 0 to exit
 * 1 to check if a string is in lowercase
 * 2 to sum the digits of a number
 * 3 to finds how many letters in the 1st word exist in the 2nd word .
 *
 * Input: It gets the server ip through the arguments
 * Output: returns the output of the given operation.
 *
 *  Copyright © 2018 Tasneem Abu Odeh. All rights reserved.
 */

//include(s) section.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "/usr/include/rpc/rpc.h"
#include "ex7.h" /*as generated by rpcgen*/

//Define(s) section.
#define MSGSZ 100

//Prototype(s) section.
void small_alpha(char *message, CLIENT *cl, char *server);
void sum(CLIENT *cl, char *server);
void the_same(char *message, CLIENT *cl, char *server);

//main section.
int main(int argc, char **argv){
    char *server;
    char *message;
    CLIENT *cl;
    
    if(argc != 2){
        fprintf(stderr, "Usage: %s <host>\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    server = argv[1];
    
    // Establishing connection with the server
    cl = clnt_create(server, REMOTE_PROG, MESSAGEVERS, "tcp");
    if (cl == NULL){
        clnt_pcreateerror(server);
        exit(EXIT_FAILURE);
    }
    // Allocating memory for the message.
    message = (char *)malloc(MSGSZ*sizeof(char));
    if(message == NULL){
        perror("Cannot allocate memory.");
        exit(EXIT_FAILURE);
    }
    
    //Handling input
    int input;
    scanf("%d", &input);
    while (input != 0) {
        if (input == 1)
            small_alpha(message,cl,server);
        else if (input == 2) {
            sum(cl,server);
        }
        else if (input == 3) {
            the_same(message,cl,server);
        }
        scanf("%d", &input);
    }
    
    // Freeing allocated memory and closing the connection.
    free(message);
    clnt_destroy(cl);
    
    exit(EXIT_SUCCESS);
}

//------------------------------------------------------------------------
////This function asks user for input, puts it into a string,
// and sends it to server to check if it has only small letters.
// it prints the result to the user.

void small_alpha(char *message, CLIENT *cl, char *server){
    puts("Please enter a string:");
    int *result;
    scanf("%s", message);
    result = small_alpha_1(&message, cl);
    if (result == NULL)
    {
        clnt_perror(cl, server);
        exit(EXIT_FAILURE);
    }
    if(*result)
        printf("\"%s\" it has only small letters.\n",message);
    else
        printf("\"%s\" it has also big letters .\n",message);
    
}

//------------------------------------------------------------------------
//This function asks user for a number,
// and sends it to server to sum it's digits.
// it prints the result to the user.

void sum(CLIENT *cl, char *server){
    puts("Please enter a number:");
    double *result;
    double number;
    scanf("%lf", &number);
    result = sum_1(&number, cl);
    printf("The digits's sum of %lf is %lf\n",number ,*result);
}

//------------------------------------------------------------------------
//This function gets input from user in this format:
//       <word> <space> <word>
// it sends it to server and prints out the result of
// how many letters which exist in the first word are also exist in the
// second word.

void the_same(char *message, CLIENT *cl, char *server){
    puts("Please enter a text:");
    int *result;
    char text;
    
    sscanf("%c", message, &text);
    sprintf(message,"%s %c",message,text);
    result = the_same_1(&message, cl);
    if (result == NULL){
        clnt_perror(cl, server);
        exit(EXIT_FAILURE);
    }
    printf("The number of the letters which have been existing in the first and the second word = %d\n", *result);
}
