/*
 * Pure C 2019
 * ex7a1.c
 *
 * This is the rpc server.
 *
 * Created on: Dec 27, 2018
 *        Created by Tasneem Abu Odeh - id: 314902685 - login: tasnimab.
 *             Jouana Nusralla - id:312315104 - login: jouananu.
 *
 * This is a rpc server, which has 3 functions that can:
 * Check lowercase, Sum the digits of a number, Find how many letters in the
 * 1st word exist in the 2nd word
 *
 * Input: It gets messages from client.
 * Output: It sends messages to the client.
 *
 *  Copyright © 2018 Tasneem Abu Odeh. All rights reserved.
 *
 */


//include(s) section.
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "/usr/include/rpc/rpc.h"
#include "ex7.h" /*as generated by rpcgen*/

//Define(s) section.
#define MSGSZ 100

//------------------------------------------------------------------------
//This function gets a string (message) from client, the message
// contains a string, it checks whether the string is has only
// lowecase letters.
// it returns 1 if it only has lowercase letters, 0 otherwise.

int * small_alpha_1_svc(char ** msg, struct svc_req *foo){
    puts("Server: Checking if all the letters in the word are small ones.");
    static int result;         /* must be static  ! */
    result = 0;
    // Start from leftmost and rightmost corners of str
    int l = 0;
    
    // Keep comparing characters while they are same
    while (l < strlen(*msg)) {
        if (!islower((*msg)[l])) {
            result = 1;
            break;
        }
    }
    return (&result);
}

//------------------------------------------------------------------------
//This function gets a pointer to a double, it sums it's digits.
//returns it to the client.

double * sum_1_svc(double *x, struct svc_req *foo) {
    puts("Server: Calculating the sum of the digits.");
    static double result;
    result = 0; //reseting for the next time this func is called
    
    int digit;
    digit = (int)*x;
    
    while (digit > 0) {
        digit = digit%10;
        result = result + digit;
        digit /= 10;
        
    }
    return (&result);
}

//------------------------------------------------------------------------

//This function gets a string (message) from client, the message
// contains a string in this format:
//       <operation> <number1> <number2>
// it calculates it depends on the given operation and returns it.

int * the_same_1_svc(char ** msg, struct svc_req *foo) {
    puts("Server: Finding the letters which exist in the first and second word.");
    static int result;         /* must be static  ! */
    result = 0;
    size_t length;
    int last = 0;
    length = strlen(*msg);
    for(int i = 0; i < length; i++){
        if((*msg)[i] != ' '){
            if(last == 0)
                result++;
            else
                last = 1;
        }
        else last = 0;
        
    }
    return (&result);
}

